version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "town-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nejano5u1lmu"
s3_prefix = "town-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

